name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: johndoe
          POSTGRES_PASSWORD: randompassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U johndoe" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm && npm install -g prettier && pnpm install

      - name: Check formatting with Prettier
        run: pnpm prettier:format

      - name: Check formatting with ESLint
        run: pnpm lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run database migrations and seed
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgres://johndoe:randompassword@localhost:5432/mydb

      - name: Build Next.js application
        run: pnpm run build

      - name: Start Next.js application
        run: pnpm start &
        env:
          DATABASE_URL: postgres://johndoe:randompassword@localhost:5432/mydb

      - name: Wait for the application to start
        run: sleep 10

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
